// Code generated by goctl. DO NOT EDIT.
// Source: car.proto

package server

import (
	"context"

	"gozero/car/api/car/v1"
	"gozero/car/internal/logic/car"
	"gozero/car/internal/svc"
)

type CarServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedCarServer
}

func NewCarServer(svcCtx *svc.ServiceContext) *CarServer {
	return &CarServer{
		svcCtx: svcCtx,
	}
}

func (s *CarServer) Ping(ctx context.Context, in *v1.Request) (*v1.Response, error) {
	l := carlogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
