// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: hello_w/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NiHao_SayHello_FullMethodName     = "/NiHao/SayHello"
	NiHao_SayHelloAgin_FullMethodName = "/NiHao/SayHelloAgin"
)

// NiHaoClient is the client API for NiHao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NiHaoClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloAgin(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type niHaoClient struct {
	cc grpc.ClientConnInterface
}

func NewNiHaoClient(cc grpc.ClientConnInterface) NiHaoClient {
	return &niHaoClient{cc}
}

func (c *niHaoClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, NiHao_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *niHaoClient) SayHelloAgin(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, NiHao_SayHelloAgin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NiHaoServer is the server API for NiHao service.
// All implementations must embed UnimplementedNiHaoServer
// for forward compatibility
type NiHaoServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	SayHelloAgin(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedNiHaoServer()
}

// UnimplementedNiHaoServer must be embedded to have forward compatible implementations.
type UnimplementedNiHaoServer struct {
}

func (UnimplementedNiHaoServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedNiHaoServer) SayHelloAgin(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgin not implemented")
}
func (UnimplementedNiHaoServer) mustEmbedUnimplementedNiHaoServer() {}

// UnsafeNiHaoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NiHaoServer will
// result in compilation errors.
type UnsafeNiHaoServer interface {
	mustEmbedUnimplementedNiHaoServer()
}

func RegisterNiHaoServer(s grpc.ServiceRegistrar, srv NiHaoServer) {
	s.RegisterService(&NiHao_ServiceDesc, srv)
}

func _NiHao_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiHaoServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiHao_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiHaoServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NiHao_SayHelloAgin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiHaoServer).SayHelloAgin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NiHao_SayHelloAgin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiHaoServer).SayHelloAgin(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NiHao_ServiceDesc is the grpc.ServiceDesc for NiHao service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NiHao_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NiHao",
	HandlerType: (*NiHaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _NiHao_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgin",
			Handler:    _NiHao_SayHelloAgin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_w/hello.proto",
}
