// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-demo/internal/service"
)

// Injectors from wire.go:

func InitEvent(pp string) (service.Event, func(), error) {
	message, cleanup, err := service.NewMessage(pp)
	if err != nil {
		return service.Event{}, nil, err
	}
	greeter, cleanup2 := service.NewGreeter(message)
	event, err := service.NewEvent(greeter)
	if err != nil {
		cleanup2()
		cleanup()
		return service.Event{}, nil, err
	}
	return event, func() {
		cleanup2()
		cleanup()
	}, nil
}
