// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"gozero/gateway/api/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = v1.Request
	Response = v1.Response

	User interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
